language: python
python:
  - "2.7"
  - "3.4"

before_install:
  - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/anaconda
  - export PATH=~/anaconda/bin:$PATH
  - conda update --yes --quiet conda

install:
  - conda create --yes -q -n pyenv python=$TRAVIS_PYTHON_VERSION pip nose pyyaml
  - source activate pyenv

script:
  - nosetests
